export default {
    mapsNames: {
        FUTUREALIEN: "futureAlienCharMap",
        SQUIGGLE6: "squiggle6CharMap",
        SQUIGGLE5: "squiggle5CharMap",
        ASIANSTYLE2: "asianStyle2CharMap",
        ASIANSTYLE: "asianStyleCharMap",
        SQUARES: "squaresCharMap",
        SQUIGGLE4: "squiggle4CharMap",
        NEON: "neonCharMap",
        SQUIGGLE3: "squiggle3CharMap",
        MONOSPACE: "monospaceCharMap",
        BOLDITALIC: "boldItalicCharMap",
        BOLD: "boldCharMap",
        BOLDSANS: "boldSansCharMap",
        ITALIC: "italicCharMap",
        SQUIGGLE2: "squiggle2CharMap",
        CURRENCY: "currencyCharMap",
        SYMBOLS: "symbolsCharMap",
        GREEK: "greekCharMap",
        BENTTEXT: "bentTextCharMap",
        UPPERANGLES: "upperAnglesCharMap",
        SUBSCRIPT: "subscriptCharMap",
        SUPERSCRIPT: "superscriptCharMap",
        SQUIGGLE: "squiggleCharMap",
        DOUBLESTRUCK: "doubleStruckCharMap",
        MEDIEVAL: "medievalCharMap",
        INVERTEDSQUARES: "invertedSquaresCharMap",
        CURSIVE: "cursiveCharMap",
        OLDENGLISH: "oldEnglishCharMap",
        WIDETEXT: "wideTextCharMap",
    }
}